### ISSUE TITLE
No validator in the "Add new meal form" lead to a Webpack errror during build process

### ISSUE THREAD

**Issue by pierre-simplon** [HeySugar/hey-sugar-app#4]
# Prerequisites

- [x] I am running the latest version commit 48fb379d95d3b23f2d8332b7760e7924a35cb364
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository 

# Expected Behavior

As a user when I add a new Meal/snack directly from a new measurement and if I don't input any nutrition value I should be warned to fill this mandatory information.

# Current Behavior

it's still possible to add the Meal, there is no warning and it will later lead to build error.

# Failure Information

 WebpackError: TypeError: Cannot read property 'carbohydrates' of null

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1

Click on + "Create a new record"

2. step 2

Fill blood sugar information, Mood, Time log, etc...

3. step 3

Click on Add "New Food" and Fill Name, Meal type and click on "Close" Button

4. step 4

Click on blue "Publish button" to record the new measure

## Context

* Operating System: Ubuntu
* Browser: Firefox 76.0.1 (64 bits)

## Failure Logs

10:25:07 AM: failed Building static HTML for pages - 3.720s
10:25:07 AM: 
10:25:07 AM: error Building static HTML failed for path "/result/0f7da03a-6283-5bc2-9389-290c99c52e30"
10:25:07 AM: 
10:25:07 AM: 
10:25:07 AM: 
10:25:07 AM:   WebpackError: TypeError: Cannot read property 'carbohydrates' of null
10:25:07 AM:   
10:25:07 AM:   - build-html.js:110 doBuildPages
10:25:07 AM:     [hey-sugar-client]/[gatsby]/dist/commands/build-html.js:110:24
10:25:07 AM:   
10:25:07 AM: 
10:25:07 AM: 
10:25:07 AM: error Command failed with exit code 1.
10:25:07 AM: 
10:25:07 AM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:25:07 AM: ​
10:25:07 AM: ┌─────────────────────────────┐
10:25:07 AM: │   "build.command" failed    │
10:25:07 AM: └─────────────────────────────┘
10:25:07 AM: ​
10:25:07 AM:   Error message
10:25:07 AM:   Command failed with exit code 1: yarn build
10:25:07 AM: ​
10:25:07 AM:   Error location
10:25:07 AM:   In build.command from netlify.toml:
10:25:07 AM:   yarn build
10:25:07 AM: ​
10:25:07 AM:   Resolved config
10:25:07 AM:   build:
10:25:07 AM:     base: /opt/build/repo/hey-sugar-client
10:25:07 AM:     command: yarn build
10:25:07 AM:     publish: /opt/build/repo/hey-sugar-client/public
10:25:07 AM: Caching artifacts
10:25:07 AM: Started saving node modules
10:25:07 AM: Finished saving node modules
10:25:07 AM: Started saving build plugins
10:25:07 AM: Finished saving build plugins
10:25:07 AM: Started saving yarn cache
10:25:07 AM: Finished saving yarn cache
10:25:07 AM: Started saving pip cache
10:25:07 AM: Finished saving pip cache
10:25:07 AM: Started saving emacs cask dependencies
10:25:07 AM: Finished saving emacs cask dependencies
10:25:07 AM: Started saving maven dependencies
10:25:07 AM: Finished saving maven dependencies
10:25:07 AM: Started saving boot dependencies
10:25:07 AM: Finished saving boot dependencies
10:25:07 AM: Started saving go dependencies
10:25:07 AM: Finished saving go dependencies
10:25:07 AM: Error running command: Build script returned non-zero exit code: 1
10:25:07 AM: Failing build: Failed to build site
10:25:08 AM: Failed during stage 'building site': Build script returned non-zero exit code: 1
10:25:09 AM: Finished processing build request in 2m7.199827195s

**Comment by jamie-endeavour** [comment]
Thanks for raising this Pierre. 

I’m away from the computer at the moment but when I get back I’ll triage it I think it’s just a case of updating the document validation on the Sanity Plugin. 

I can probably take a look at this as soon as this evening because the build shouldn’t break like that. 

Thanks again!

**Comment by jamie-endeavour** [comment]
Okay so this is now fixed. You will need to bump your version of the Gatsby Theme and the Sanity Plugin to 0.3.0 to get the updates. You will also need to re-deploy the GraphQL endpoint otherwise netlify builds will fail. 

So, the steps to upgrade are as follows:

**hey-sugar-tracker/package.json**
```
// Bump the sanity plugin to 0.3.0
"@hey-sugar/sanity-plugin-hey-sugar-schema": "0.3.0",
```

Then run `yarn install` or `npm install`

**hey-sugar-client/package.json**
```
// Bump the gatsby theme version to 0.3.0
"@hey-sugar/gatsby-theme-heysugar": "0.3.0",
```

Then run `yarn install` or `npm install`

Once you have upgraded the packages, cd into the `hey-sugar-tracker` folder through your terminal and run the following sanity commands:

```
# Deploy the GraphQL Endpoint - Say "yes" to any warnings that appear
sanity graphql deploy

# Deploy the changes your hosted Sanity tracker
sanity deploy 
```

Finally push the changes to your repository and the Netlify deploy should take it from there.
